# Day 1: Environment Check & Setup

**Duration:** 30 minutes  
**Objective:** Verify your development environment and understand the workshop toolkit

## 🎯 Learning Goals
By the end of this notebook, you will:
- Understand how to verify Python package installations
- Know how to check GPU availability for deep learning
- Be familiar with basic PyTorch tensor operations
- Understand the importance of environment consistency in AI projects

## 📚 Key Concepts
- **Virtual Environments**: Isolated Python environments for project dependencies
- **GPU Computing**: Using graphics cards to accelerate machine learning computations
- **Package Management**: Managing Python libraries and their versions

---

## Section 1: Python Environment Verification

### 🔍 What We're Doing
First, we need to verify that your Python environment is correctly set up. This includes checking:
- Python version (should be 3.10+)
- Virtual environment activation
- Package availability

### 💡 Why This Matters
Environment consistency is crucial in AI/ML projects. Different Python or package versions can lead to:
- Code that works on one machine but fails on another
- Subtle differences in model behavior
- Incompatible dependencies

### 📝 Your Task
Complete the code below to check your Python version and print the executable path.

In [1]:
# TODO: Import the sys module
import sys

# TODO: Print the Python version using sys.version
print(f"Python version: {sys.version}")

# TODO: Print the Python executable path using sys.executable
print(f"Python executable: {sys.executable}")

# TODO: Check if Python version is 3.10 or higher
version_info = sys.version_info
if version_info.major == 3 and version_info.minor >= 10:
    print("✅ Python version is compatible!")
else:
    print("❌ Python version is too old. Please upgrade to 3.10+")

Python version: 3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]
Python executable: /usr/bin/python3
✅ Python version is compatible!


### 🔧 Package Import Verification

Now let's verify that all required packages are installed. If any imports fail, you'll need to install them using `pip install -r requirements.txt`.

**Research Task:** Look up what each of these packages does:
- `torch`: ?
- `transformers`: ?
- `cv2` (opencv): ?
- `gradio`: ?

In [2]:
# TODO: Try importing all required packages and handle any ImportError
required_packages = {
    'torch': 'PyTorch deep learning framework',
    'transformers': 'Hugging Face transformers library',
    'cv2': 'OpenCV computer vision library',
    'numpy': 'Numerical computing library',
    'pandas': 'Data manipulation library',
    'matplotlib': 'Plotting library',
    'gradio': 'Web UI library for ML demos'
}

import_results = []

for package_name, description in required_packages.items():
    try:
        # TODO: Use __import__() or importlib to import the package
        __import__(package_name)

        print(f"✅ {package_name} - {description}")
        import_results.append((package_name, True))
    except ImportError as e:
        # TODO: Handle the import error and print a helpful message
        print(f"❌ {package_name} - Missing! {description}. Error: {e}")
        import_results.append((package_name, False))

# TODO: Print summary of results
failed_imports = [pkg for pkg, success in import_results if not success]
if failed_imports:
    print(f"\n⚠️ Install missing packages: pip install {' '.join(failed_imports)}")
else:
    print("\n🎉 All packages imported successfully!")

✅ torch - PyTorch deep learning framework
✅ transformers - Hugging Face transformers library
✅ cv2 - OpenCV computer vision library
✅ numpy - Numerical computing library
✅ pandas - Data manipulation library
✅ matplotlib - Plotting library
✅ gradio - Web UI library for ML demos

🎉 All packages imported successfully!


---

## Section 2: GPU and Hardware Check

### 🔍 What We're Doing
We'll check if your system has GPU support available for accelerated computing.

### 💡 Why This Matters
- **CPU vs GPU**: CPUs are great for general computing, GPUs excel at parallel operations
- **Deep Learning**: Neural networks involve massive matrix operations that GPUs can accelerate 10-100x
- **CUDA**: NVIDIA's parallel computing platform that PyTorch uses

### 📝 Your Task
Research and implement GPU detection code.

In [3]:
import torch

# TODO: Check if CUDA is available
cuda_available = torch.cuda.is_available()  # Use torch.cuda method

print(f"CUDA available: {cuda_available}")

if cuda_available:
    # TODO: Get GPU device name
    gpu_name = torch.cuda.get_device_name(0)  # Use torch.cuda method
    print(f"GPU device: {gpu_name}")

    # TODO: Get CUDA version
    cuda_version = torch.version.cuda  # Use torch.version attribute
    print(f"CUDA version: {cuda_version}")

    # TODO: Get number of available GPUs
    gpu_count = torch.cuda.device_count()  # Use torch.cuda method
    print(f"Number of GPUs: {gpu_count}")

else:
    print("⚠️ No GPU available - using CPU")
    print("💡 Consider using Google Colab for free GPU access")

# TODO: Set device for computations
device = torch.device('cuda' if cuda_available else 'cpu')  # torch.device
print(f"\nUsing device: {device}")

CUDA available: False
⚠️ No GPU available - using CPU
💡 Consider using Google Colab for free GPU access

Using device: cpu


### 🧪 Memory and Performance Check

Let's check available memory and run a simple performance test.

**Research Questions:**
1. What's the difference between RAM and VRAM?
2. Why might you run out of GPU memory during training?
3. What strategies can you use if you have limited GPU memory?

In [ ]:
import time
import psutil  # You may need to install this: pip install psutil

# System RAM check
ram_info = psutil.virtual_memory()
print(f"Total RAM: {ram_info.total / (1024**3):.1f} GB")
print(f"Available RAM: {ram_info.available / (1024**3):.1f} GB")

# GPU memory check (if available)
if cuda_available:
    # TODO: Get GPU memory info using torch.cuda methods
    total_memory = ___  # torch.cuda.get_device_properties(0).total_memory
    allocated_memory = ___  # torch.cuda.memory_allocated(0)

    print(f"\nGPU Total Memory: {total_memory / (1024**3):.1f} GB")
    print(f"GPU Allocated Memory: {allocated_memory / (1024**3):.1f} GB")

# Simple performance test
print("\n🔬 Running performance test...")

# TODO: Create two large random tensors
size = 1000
a = torch.randn(size, size)  # Create on CPU first
b = torch.randn(size, size)

# CPU timing
start_time = time.time()
# TODO: Perform matrix multiplication on CPU
result_cpu = ___  # torch.matmul or @ operator
cpu_time = time.time() - start_time

print(f"CPU computation time: {cpu_time:.4f} seconds")

# GPU timing (if available)
if cuda_available:
    # TODO: Move tensors to GPU
    a_gpu = ___  # tensor.to(device) or tensor.cuda()
    b_gpu = ___

    # TODO: Warm up GPU (run operation once)
    _ = torch.matmul(a_gpu, b_gpu)
    torch.cuda.synchronize()  # Wait for GPU to finish

    start_time = time.time()
    # TODO: Perform matrix multiplication on GPU
    result_gpu = ___
    torch.cuda.synchronize()
    gpu_time = time.time() - start_time

    print(f"GPU computation time: {gpu_time:.4f} seconds")
    print(f"Speedup: {cpu_time/gpu_time:.1f}x faster on GPU")

print("✅ Performance test complete!")

---

## Section 3: Basic PyTorch Operations

### 🔍 What We're Learning
PyTorch tensors are the fundamental data structure for deep learning. They're similar to NumPy arrays but can run on GPUs.

### 💡 Key Concepts
- **Tensors**: Multi-dimensional arrays that can store data and gradients
- **Device placement**: Moving tensors between CPU and GPU
- **Automatic differentiation**: Computing gradients automatically

### 📝 Your Tasks
Complete the tensor operation exercises below.

In [5]:
import torch

print("=== Tensor Creation ===")

# TODO: Create different types of tensors
# 1. From a Python list
list_tensor = torch.tensor([1,2,3,4,5])  # torch.tensor([1, 2, 3, 4, 5])

# 2. Zeros tensor of shape (3, 4)
zeros_tensor = torch.zeros(3,4)  # torch.zeros(...)

# 3. Random tensor of shape (2, 3, 4)
random_tensor = torch.randn(2,3,4)  # torch.randn(...)

# 4. Tensor of ones with same shape as random_tensor
ones_like = torch.ones_like(random_tensor)  # torch.ones_like(...)

print(f"List tensor: {list_tensor}")
print(f"Zeros shape: {zeros_tensor.shape}")
print(f"Random shape: {random_tensor.shape}")
print(f"Ones like shape: {ones_like.shape}")

print("\n=== Tensor Properties ===")
# TODO: Print tensor properties
x = torch.randn(3, 4, 5)
print(f"Shape: {x.shape}")  # x.shape or x.size()
print(f"Data type: {x.dtype}")  # x.dtype
print(f"Device: {x.device}")  # x.device
print(f"Number of elements: {x.numel()}")  # x.numel()
print(f"Number of dimensions: {x.ndim}")  # x.ndim or len(x.shape)

=== Tensor Creation ===
List tensor: tensor([1, 2, 3, 4, 5])
Zeros shape: torch.Size([3, 4])
Random shape: torch.Size([2, 3, 4])
Ones like shape: torch.Size([2, 3, 4])

=== Tensor Properties ===
Shape: torch.Size([3, 4, 5])
Data type: torch.float32
Device: cpu
Number of elements: 60
Number of dimensions: 3


In [6]:
print("=== Tensor Operations ===")  #

# Create sample tensors
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"Tensor a:\n{a}")
print(f"Tensor b:\n{b}")

# TODO: Perform basic operations
# 1. Element-wise addition
addition = a + b  # a + b or torch.add(a, b)

# 2. Element-wise multiplication
element_mult = a * b  # a * b

# 3. Matrix multiplication
matrix_mult = torch.matmul(a, b)  # torch.matmul(a, b) or a @ b

# 4. Transpose of tensor a
transpose = a.T  # a.T or torch.transpose(a, 0, 1)

print(f"\nAddition:\n{addition}")
print(f"Element-wise multiplication:\n{element_mult}")
print(f"Matrix multiplication:\n{matrix_mult}")
print(f"Transpose of a:\n{transpose}")

# TODO: Aggregation operations
data = torch.randn(4, 3)
print(f"\nData tensor:\n{data}")

# Calculate statistics
mean_val = data.mean()  # data.mean()
std_val = data.std()   # data.std()
max_val = data.max()   # data.max()
min_val = data.min()   # data.min()
sum_val = data.sum()   # data.sum()

print(f"Mean: {mean_val:.4f}")
print(f"Std: {std_val:.4f}")
print(f"Max: {max_val:.4f}")
print(f"Min: {min_val:.4f}")
print(f"Sum: {sum_val:.4f}")

=== Tensor Operations ===
Tensor a:
tensor([[1., 2.],
        [3., 4.]])
Tensor b:
tensor([[5., 6.],
        [7., 8.]])

Addition:
tensor([[ 6.,  8.],
        [10., 12.]])
Element-wise multiplication:
tensor([[ 5., 12.],
        [21., 32.]])
Matrix multiplication:
tensor([[19., 22.],
        [43., 50.]])
Transpose of a:
tensor([[1., 3.],
        [2., 4.]])

Data tensor:
tensor([[ 2.4582,  1.7404, -0.4105],
        [-0.1028,  0.4397,  0.9510],
        [-0.4304,  1.3314, -0.7306],
        [-1.7933,  0.3096,  0.7264]])
Mean: 0.3741
Std: 1.1678
Max: 2.4582
Min: -1.7933
Sum: 4.4890


### 🚀 Advanced Exercise: Device Movement

Practice moving tensors between devices (CPU ↔ GPU).

**Research Questions:**
1. When should you move data to GPU vs keep on CPU?
2. What happens if you try to operate on tensors on different devices?
3. How does data transfer time compare to computation time?

In [7]:
# Create a tensor on CPU
cpu_tensor = torch.randn(100, 100)
print(f"Original device: {cpu_tensor.device}")

if torch.cuda.is_available():
    # TODO: Move tensor to GPU using different methods
    # Method 1: .cuda()
    gpu_tensor1 = cpu_tensor.cuda()  # cpu_tensor.cuda()

    # Method 2: .to(device)
    gpu_tensor2 = cpu_tensor.to('cuda')  # cpu_tensor.to('cuda')

    # Method 3: .to(device) with device variable
    device = torch.device('cuda')
    gpu_tensor3 = cpu_tensor.to(device)  # cpu_tensor.to(device)

    print(f"GPU tensor device: {gpu_tensor1.device}")

    # TODO: Move back to CPU
    back_to_cpu = gpu_tensor1.cpu()  # gpu_tensor1.cpu()
    print(f"Back to CPU: {back_to_cpu.device}")

    # TODO: Try operations between tensors on different devices
    # This should raise an error - catch it!
    try:
        result = cpu_tensor + gpu_tensor1  # This will fail!
    except Exception as e:
        print(f"\n❌ Error mixing devices: {type(e).__name__}")
        print(f"Solution: Move both tensors to same device")

        # TODO: Fix by moving both to same device
        result = cpu_tensor.cuda() + gpu_tensor1
        print(f"✅ Fixed! Result device: {result.device}")

else:
    print("No GPU available - tensor will stay on CPU")
    print("💡 In production, always check device availability before moving tensors")

Original device: cpu
No GPU available - tensor will stay on CPU
💡 In production, always check device availability before moving tensors


---

## Section 4: Environment Best Practices

### 📝 Reflection Questions

Answer these questions based on what you've learned:

1. **Why is it important to check your environment before starting an AI project?**
   
   *Your answer here*

2. **What are three advantages of using GPU for deep learning?**
   
   *Your answer here*

3. **What would you do if you ran out of GPU memory during training?**
   
   *Your answer here*

4. **How do you ensure your code works on both CPU and GPU?**
   
   *Your answer here*

### 🎯 Environment Checklist

Mark off each item as you complete it:

- [ ] Python 3.10+ verified
- [ ] All required packages imported successfully  
- [ ] GPU availability checked
- [ ] Basic tensor operations completed
- [ ] Device movement practiced
- [ ] Performance comparison run
- [ ] Understanding of PyTorch basics confirmed

### 🔧 Troubleshooting Common Issues

If you encountered problems, research and note solutions here:

**Import Errors:**
- Problem: `ModuleNotFoundError: No module named 'torch'`
- Solution: *Your research here*

**CUDA Issues:**
- Problem: `CUDA out of memory`
- Solution: *Your research here*

**Performance Issues:**
- Problem: GPU slower than expected
- Solution: *Your research here*

---

## 🎉 Checkpoint Complete!

**What You've Accomplished:**
- ✅ Verified your development environment
- ✅ Understood hardware requirements for AI
- ✅ Learned basic PyTorch tensor operations
- ✅ Practiced device management (CPU/GPU)
- ✅ Identified potential issues and solutions

**Key Takeaways:**
1. Environment consistency is critical for reproducible AI
2. GPU acceleration can dramatically speed up deep learning
3. PyTorch tensors are the foundation of modern deep learning
4. Always check device compatibility in your code

**Next Steps:**
- Continue to the AI Refresher notebook
- Keep your environment active for the rest of Day 1
- Ask questions if anything wasn't clear!

---

**📚 Additional Resources to Explore:**
- [PyTorch Documentation](https://pytorch.org/docs/stable/index.html)
- [CUDA Programming Guide](https://docs.nvidia.com/cuda/)
- [Virtual Environments Guide](https://docs.python.org/3/tutorial/venv.html)

*Environment Setup Complete - Ready for AI Deep Dive!* 🚀

In [4]:
import time
import psutil  # You may need to install this: pip install psutil

# System RAM check
ram_info = psutil.virtual_memory()
print(f"Total RAM: {ram_info.total / (1024**3):.1f} GB")
print(f"Available RAM: {ram_info.available / (1024**3):.1f} GB")

# GPU memory check (if available)
if cuda_available:
    # TODO: Get GPU memory info using torch.cuda methods
    total_memory = torch.cuda.get_device_properties(0).total_memory  # torch.cuda.get_device_properties(0).total_memory
    allocated_memory = torch.cuda.memory_allocated(0)  # torch.cuda.memory_allocated(0)

    print(f"\nGPU Total Memory: {total_memory / (1024**3):.1f} GB")
    print(f"GPU Allocated Memory: {allocated_memory / (1024**3):.1f} GB")

# Simple performance test
print("\n🔬 Running performance test...")

# TODO: Create two large random tensors
size = 1000
a = torch.randn(size, size)  # Create on CPU first
b = torch.randn(size, size)

# CPU timing
start_time = time.time()
# TODO: Perform matrix multiplication on CPU
result_cpu = torch.matmul(a, b)  # torch.matmul or @ operator
cpu_time = time.time() - start_time

print(f"CPU computation time: {cpu_time:.4f} seconds")

# GPU timing (if available)
if cuda_available:
    # TODO: Move tensors to GPU
    a_gpu = a.to(device)  # tensor.to(device) or tensor.cuda()
    b_gpu = b.to(device)

    # TODO: Warm up GPU (run operation once)
    _ = torch.matmul(a_gpu, b_gpu)
    torch.cuda.synchronize()  # Wait for GPU to finish

    start_time = time.time()
    # TODO: Perform matrix multiplication on GPU
    result_gpu = torch.matmul(a_gpu, b_gpu)
    torch.cuda.synchronize()
    gpu_time = time.time() - start_time

    print(f"GPU computation time: {gpu_time:.4f} seconds")
    print(f"Speedup: {cpu_time/gpu_time:.1f}x faster on GPU")

print("✅ Performance test complete!")

Total RAM: 12.7 GB
Available RAM: 11.4 GB

🔬 Running performance test...
CPU computation time: 0.1497 seconds
✅ Performance test complete!
